version: '3.8'
services:
  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:latest
    hostname: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432
  keycloak-postgres:
    container_name: keycloak-postgres
    image: quay.io/keycloak/keycloak:latest
    hostname: keycloak-postgres
    environment:
      TZ: Europe/Warsaw
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: admin
    ports:
      - 10080:8080