version: '3.8'
services:
  server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    environment:
      TZ: Europe/Warsaw
    ports:
      - 8111:8111
  #    volumes:
  #      - ./data_dir:/data/teamcity_server/datadir
  #      - ./log_dir:/opt/teamcity/logs

  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent
    environment:
      TZ: Europe/Warsaw
      SERVER_URL: http://server:8111
      AGENT_NAME: regular_agent
  teamcity-minimal-agent:
    image: jetbrains/teamcity-minimal-agent
    container_name: teamcity-minimal-agent
    environment:
      TZ: Europe/Warsaw
      SERVER_URL: http://server:8111
      AGENT_NAME: minimal_agent