version: '3.8'
services:

  keycloak-simple:
    container_name: keycloak-simple
    image: jboss/keycloak:latest
    hostname: keycloak-simple-jboss
    environment:
      TZ: Europe/Warsaw
      LANG: pl_PL.UTF-8
      KEYCLOAK_USER: admin2
      KEYCLOAK_PASSWORD: admin2
    ports:
      - 8091:8080