version: "3.8"
services:
  kafka:
    hostname: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,RMOFF_DOCKER_HACK://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,RMOFF_DOCKER_HACK:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,RMOFF_DOCKER_HACK://kafka:9094
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  kouncil:
    image: consdata/kouncil:latest
    restart: always
    depends_on:
      - kafka
    environment:
      bootstrapServers: kafka:9094
      BOOTSTRAPSERVERS: kafka:9094
      BOOTSTRAP_SERVERS: kafka:9094
    ports:
      - 8888:8080