version: '3.8'
services:

  keycloak-simple:
    container_name: keycloak-simple
    image: quay.io/keycloak/keycloak:latest
    #    image: oracle/database:latest
    hostname: keycloak-simple
    environment:
      TZ: Europe/Warsaw
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 10080:8080