version: '3.8'
services:

  wildfly-simple:
    container_name: wildfly-simple
    image: jboss/wildfly:latest
    hostname: wildfly-simple
    command:
      /opt/jboss/wildfly/bin/standalone.sh -bmanagement=0.0.0.0 -b 0.0.0.0
    environment:
      TZ: Europe/Warsaw
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990