version: "3.8"

#networks:
#  dockernet:
#    external: true

#networks:
#networks:
#  front-tier:
#    driver: bridge
#  back-tier:
#    driver: bridge
#  myMac:
#    driver: macvlan
#    driver_opts:
#      parent: eth0
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.1.0/24
#          gateway: 192.168.1.1

services:
#  ubuntu:
#    image: ubuntu
#    container_name: ubuntu
  server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    environment:
      TZ: Europe/Warsaw
    ports:
      - 8111:8111
  #    volumes:
  #      - ./data_dir:/data/teamcity_server/datadir
  #      - ./log_dir:/opt/teamcity/logs
  teamcity-agent:
    container_name: teamcity-agent
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=regular_agent
      - TZ=Europe/Warsaw
  teamcity-minimal-agent:
    container_name: teamcity-minimal-agent
    image: jetbrains/teamcity-minimal-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=minimal_agent
      - TZ=Europe/Warsaw