version: "3.8"

#networks:
#  dockernet:
#    external: true

#networks:
networks:
  main_network:
    driver: bridge


services:
  server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    environment:
      TZ: Europe/Warsaw
    ports:
      - 8111:8111
    networks:
      [main_network]
  teamcity-minimal-agent:
    container_name: teamcity-minimal-agent
    image: jetbrains/teamcity-minimal-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=minimal_agent
      - TZ=Europe/Warsaw
    networks:
      [main_network]