version: '3.8'
services:

  postgres-db:
    container_name: postgres_data
    image: postgres:latest
    hostname: postgres-db
    environment:
      TZ: Europe/Warsaw
      POSTGRES_PASSWORD: admin
    volumes:
      - ./sql/initSchemat.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"